[package]
name = "day-twenty-one"
version = "0.1.0"
authors = ["Anthony Williams <hi@antw.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intcode = { path = "../intcode" }
