[package]
name = "day-twenty"
version = "0.1.0"
authors = ["Anthony Williams <hi@antw.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pathfinding = "2.0.3"
